stripe-simple-example-app/stripe-simple-example-app/Models/Cart.cs
using System.ComponentModel.DataAnnotations;

namespace stripe_simple_example_app.Models
{
    public class Cart
    {
        [Required(ErrorMessage = "Champs requis !")]
        public string? Name { get; set; }
        public List<Item>? Items { get; set; }
    }
}

stripe-simple-example-app/stripe-simple-example-app/Models/Item.cs
namespace stripe_simple_example_app.Models
{
    public class Item
    {
            public string? Id { get; set; }
            public string? Title { get; set; }
            public long Price { get; set; }
            public int Quantity { get; set; }
            public bool IsSelected { get; set; }
    }
}

stripe-simple-example-app/stripe-simple-example-app/Controllers/StripeController.cs
using Microsoft.AspNetCore.Mvc;
using Stripe;
using stripe_simple_example_app.Models;
using System.Reflection;

namespace stripe_simple_example_app.Controllers
{
    public class StripeController : Controller
    {
        private Models.Cart cart;

        public StripeController() 
        {
            cart = new Models.Cart()
            {
                Items = new List<Item>()
                {
                    new Models.Item() { Id = "1", Title = "Laptop", Price = 1000, Quantity = 0},
                    new Models.Item() { Id = "2", Title = "iPhone", Price = 500, Quantity = 0},
                    new Models.Item() { Id = "3", Title = "Mouse", Price = 30, Quantity = 0}
                }
            }
;
        }

        [HttpGet]
        public IActionResult Cart()
        {
            return View(cart);
        }

        [HttpPost]
        public IActionResult Cart(Models.Cart _cart)
        {
            if (ModelState.IsValid)
            {
                long totalAmount = 0;

                foreach (Models.Item item in _cart.Items)
                {
                    if(item.IsSelected)
                        totalAmount += item.Price * item.Quantity;
                }

                if(totalAmount == 0)
                    return View(_cart);
                else
                    return RedirectToAction("Invoice", new { _totalAmount = totalAmount, _name = _cart.Name });
            }
            
            return View(_cart);
        }

        [HttpGet]
        public IActionResult Invoice(long _totalAmount, string _name)
        {
            ViewBag.TotalAmount = _totalAmount;
            ViewBag.TotalAmountStripe = _totalAmount * 100;
            ViewBag.Name = _name;
            return View();
        }

        [HttpPost]
        public IActionResult Invoice(string stripeToken, string stripeEmail)
        {
            /* CLIENT */
            CustomerCreateOptions optionsCustomer = new CustomerCreateOptions
            {
                Email = stripeEmail,
                Name = Request.Form["name"],
            };

            CustomerService serviceCustomer = new CustomerService();
            Customer customer = serviceCustomer.Create(optionsCustomer);

            /* FACTURE */
            ChargeCreateOptions optionsCharge = new ChargeCreateOptions
            {
                Amount = long.Parse(Request.Form["amount"]) * 100,
                Currency = "CAD",
                Description = "Facture",
                Source = stripeToken,
                ReceiptEmail = stripeEmail,
            };

            ChargeService service = new ChargeService();
            Charge charge = service.Create(optionsCharge);

            /* TRAITEMENT */
            if (charge.Status == "succeeded")
            {
                string BalanceTransactionId = charge.BalanceTransactionId;
                ViewBag.AmountPaid = charge.Amount / 100;
                ViewBag.BalanceTxId = BalanceTransactionId;
                ViewBag.Customer = customer.Name;

                return View("Success");
            }

            return View("Error");
        }
    }
}

stripe-simple-example-app/stripe-simple-example-app/Views/Shared/_Layout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0/css/bootstrap.min.css" integrity="sha512-NZ19NrT58XPK5sXqXnnvtf9T5kLXSzGQlVZL9taZWeTBtXoN3xIfTdxbkQh6QSoJfJgpojRqMfhyqBAAEeiXcA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="container-fluid p-5 w-100">
        @RenderBody()
    </div>
</body>
</html>

stripe-simple-example-app/stripe-simple-example-app/Views/Stripe/Cart.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "_Layout";
    ViewBag.Title = "Panier";
}

@model stripe_simple_example_app.Models.Cart


<div class="card">
    <div class="card-header">
        <h3>Panier</h3>
    </div>
    <div class="card-body">
        <form asp-action="Cart">

            <div class="form-group">
                <label class="form-label" asp-for="Name">Nom du client</label>
                <input class="form-control" type="text" asp-for="Name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Sélectionner</th>
                        <th scope="col">ID</th>
                        <th scope="col">Titre</th>
                        <th scope="col">Prix unitaire</th>
                        <th scope="col">Quantité</th>
                    </tr>
                </thead>

                <tbody>
                    @for (int idx = 0; idx < Model.Items.Count(); idx++)
                    {
                        <tr>
                            <td><input class="form-check-input" type="checkbox" asp-for="@Model.Items[idx].IsSelected" /></td>
                            <td>@Model.Items[idx].Id <input type="hidden" asp-for="@Model.Items[idx].Id" value="@Model.Items[idx].Id" /></td>
                            <td>@Model.Items[idx].Title <input type="hidden" asp-for="@Model.Items[idx].Title" value="@Model.Items[idx].Title" /></td>
                            <td>@Model.Items[idx].Price <input type="hidden" asp-for="@Model.Items[idx].Price" value="@Model.Items[idx].Price" /></td>
                            <td><input class="form-control" type="number" asp-for="@Model.Items[idx].Quantity" min="0" /></td>
                        </tr>
                    }
                </tbody>
            </table>

            <button type="submit" class="btn btn-primary"><i class="fa-solid fa-cart-shopping"></i> Suivant</button>

        </form>
    </div>
</div>

stripe-simple-example-app/stripe-simple-example-app/Views/Stripe/Invoice.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
    ViewBag.Title = "Facture";
}

@using Microsoft.Extensions.Options
@inject IOptions<stripe_simple_example_app.StripeSettings> Stripe

<div class="card">
    <div class="card-header">
        <h3>Facture</h3>
    </div>
    <div class="card-body">
        <div class="alert alert-primary" role="alert">
            Le total du montant à payer est de : <b>@ViewBag.TotalAmount $ CA</b>
        </div>

        <form asp-action="Processing" asp-controller="Stripe" method="post">
            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-key="@Stripe.Value.PublicKey"
                    data-amount="@ViewBag.TotalAmountStripe"
                    data-description="IT Store !"
                    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
                    data-locale="fr"
                    data-zip-code="false"
                    data-label="Payer !">
            </script>
            <script>
                document.getElementsByClassName("stripe-button-el")[0].style.display = 'none';
            </script>
            <input type="hidden" name="amount" value="@ViewBag.TotalAmount" />
            <input type="hidden" name="name" value="@ViewBag.Name" />
            <button type="submit" class="btn btn-success"><i class="fa-regular fa-credit-card"></i> Payer !</button>
        </form>
    </div>
</div>

stripe-simple-example-app/stripe-simple-example-app/Views/Stripe/Success.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    Layout = "_Layout";
    ViewBag.Title = "Succès !";
}

<div class="card">
    <div class="card-header">
        <h3>Résultat</h3>
    </div>
    <div class="card-body">
        <div class="alert alert-success" role="alert">
            <b>Super !</b> Le processus de paiement s'est effectué avec succès.
        </div>

        <div class="alert alert-info" role="alert">
            <b>Client :</b> @ViewBag.Name | <b>Total Payé:</b> @ViewBag.AmountPaid
        </div>

        <a class="btn btn-primary" href="~/Stripe/Cart"><i class="fa-solid fa-angle-left"></i> Retour vers le panier</a>
    </div>
</div>